uav_motion_tracking:
        x:
                k_p: 1.5
                k_i: 0.0
                k_d: 0.0
                limit_output: 9.0
        y:
                k_p: 1.5
                k_i: 0.0
                k_d: 0.0
                limit_output: 9.0
        z:
                k_p: 1.0
                k_i: 0.0
                k_d: 0.0
                limit_output: 9.0
        yaw:
                k_p: 2.0
                k_i: 0.0
                k_d: 0.0
                limit_output: 1.0
        center_cross_point_threshold: 1.0 # [m] 
        takeoff_height: 1.0 # [m]
        descending_velocity_limit: -1.5 # [m]
        heliport_height_offset: 0.3 # [m]
        landing_vertical_distance_threshold: 0.4 # [m]
        landing_vertical_distance_threshold2: 0.25 # [m], this depends on the baselink height of UAV upon the leg lowest point of UAV
        landing_level_distance_threshold: 0.6 # [m]
        waiting_height: 5.0 #[m]
controller:
        twist:
                auto_engage: false